// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemInfo.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SystemInfo.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace systemInfo {

namespace {

const ::google::protobuf::Descriptor* system_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  system_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_SystemInfo_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_SystemInfo_2eproto() {
  protobuf_AddDesc_SystemInfo_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SystemInfo.proto");
  GOOGLE_CHECK(file != NULL);
  system_descriptor_ = file->message_type(0);
  static const int system_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(system, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(system, id_),
  };
  system_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      system_descriptor_,
      system::internal_default_instance(),
      system_offsets_,
      -1,
      -1,
      -1,
      sizeof(system),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(system, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SystemInfo_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      system_descriptor_, system::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_SystemInfo_2eproto() {
  system_default_instance_.Shutdown();
  delete system_reflection_;
}

void protobuf_InitDefaults_SystemInfo_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  system_default_instance_.DefaultConstruct();
  system_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_SystemInfo_2eproto_once_);
void protobuf_InitDefaults_SystemInfo_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_SystemInfo_2eproto_once_,
                 &protobuf_InitDefaults_SystemInfo_2eproto_impl);
}
void protobuf_AddDesc_SystemInfo_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_SystemInfo_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020SystemInfo.proto\022\nsystemInfo\"\"\n\006system"
    "\022\014\n\004name\030\004 \001(\t\022\n\n\002id\030\001 \001(\005b\006proto3", 74);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SystemInfo.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SystemInfo_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_SystemInfo_2eproto_once_);
void protobuf_AddDesc_SystemInfo_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_SystemInfo_2eproto_once_,
                 &protobuf_AddDesc_SystemInfo_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SystemInfo_2eproto {
  StaticDescriptorInitializer_SystemInfo_2eproto() {
    protobuf_AddDesc_SystemInfo_2eproto();
  }
} static_descriptor_initializer_SystemInfo_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int system::kNameFieldNumber;
const int system::kIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

system::system()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_SystemInfo_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:systemInfo.system)
}

void system::InitAsDefaultInstance() {
}

system::system(const system& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:systemInfo.system)
}

void system::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0;
  _cached_size_ = 0;
}

system::~system() {
  // @@protoc_insertion_point(destructor:systemInfo.system)
  SharedDtor();
}

void system::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void system::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* system::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return system_descriptor_;
}

const system& system::default_instance() {
  protobuf_InitDefaults_SystemInfo_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<system> system_default_instance_;

system* system::New(::google::protobuf::Arena* arena) const {
  system* n = new system;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void system::Clear() {
// @@protoc_insertion_point(message_clear_start:systemInfo.system)
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_ = 0;
}

bool system::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:systemInfo.system)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 id = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_name;
        break;
      }

      // optional string name = 4;
      case 4: {
        if (tag == 34) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "systemInfo.system.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:systemInfo.system)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:systemInfo.system)
  return false;
#undef DO_
}

void system::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:systemInfo.system)
  // optional int32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // optional string name = 4;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "systemInfo.system.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->name(), output);
  }

  // @@protoc_insertion_point(serialize_end:systemInfo.system)
}

::google::protobuf::uint8* system::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:systemInfo.system)
  // optional int32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // optional string name = 4;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "systemInfo.system.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->name(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:systemInfo.system)
  return target;
}

size_t system::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:systemInfo.system)
  size_t total_size = 0;

  // optional string name = 4;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // optional int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void system::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:systemInfo.system)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const system* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const system>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:systemInfo.system)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:systemInfo.system)
    UnsafeMergeFrom(*source);
  }
}

void system::MergeFrom(const system& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:systemInfo.system)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void system::UnsafeMergeFrom(const system& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
}

void system::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:systemInfo.system)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void system::CopyFrom(const system& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:systemInfo.system)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool system::IsInitialized() const {

  return true;
}

void system::Swap(system* other) {
  if (other == this) return;
  InternalSwap(other);
}
void system::InternalSwap(system* other) {
  name_.Swap(&other->name_);
  std::swap(id_, other->id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata system::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = system_descriptor_;
  metadata.reflection = system_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// system

// optional string name = 4;
void system::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& system::name() const {
  // @@protoc_insertion_point(field_get:systemInfo.system.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void system::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:systemInfo.system.name)
}
void system::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:systemInfo.system.name)
}
void system::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:systemInfo.system.name)
}
::std::string* system::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:systemInfo.system.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* system::release_name() {
  // @@protoc_insertion_point(field_release:systemInfo.system.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void system::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:systemInfo.system.name)
}

// optional int32 id = 1;
void system::clear_id() {
  id_ = 0;
}
::google::protobuf::int32 system::id() const {
  // @@protoc_insertion_point(field_get:systemInfo.system.id)
  return id_;
}
void system::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:systemInfo.system.id)
}

inline const system* system::internal_default_instance() {
  return &system_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace systemInfo

// @@protoc_insertion_point(global_scope)
